export interface ColorScheme {
  id: string
  name: string
  primary: string
  primaryStrong: string
  primarySoft: string
  secondary: string
  secondarySoft: string
  surface: string
  surfaceStrong: string
  surfaceMuted: string
  text: string
  textMuted: string
  border: string
}

export const COLOR_SCHEMES: ColorScheme[] = [
  {
    id: 'greyscale',
    name: 'Greyscale',
    primary: '#4b4f55',
    primaryStrong: '#3b3f44',
    primarySoft: '#6a6f76',
    secondary: '#8b9097',
    secondarySoft: '#b6bbc1',
    surface: '#f5f6f7',
    surfaceStrong: '#e2e4e7',
    surfaceMuted: '#d3d6da',
    text: '#1d1f22',
    textMuted: '#5d6269',
    border: '#c3c7cc',
  },
  {
    id: 'navy',
    name: 'Navy Blue',
    primary: '#1e3a5f',
    primaryStrong: '#152d4d',
    primarySoft: '#3a6b9f',
    secondary: '#5a8ab5',
    secondarySoft: '#a3c4de',
    surface: '#f0f4f8',
    surfaceStrong: '#dce6ef',
    surfaceMuted: '#c8d6e3',
    text: '#0f1c2e',
    textMuted: '#4a6178',
    border: '#b8cad9',
  },
  {
    id: 'teal',
    name: 'Teal',
    primary: '#1a6b5a',
    primaryStrong: '#125446',
    primarySoft: '#2d9b84',
    secondary: '#5aab9a',
    secondarySoft: '#a3d4c8',
    surface: '#f0f7f5',
    surfaceStrong: '#d9ece7',
    surfaceMuted: '#c2e0d8',
    text: '#0d2b24',
    textMuted: '#3d6b5e',
    border: '#b2d4cb',
  },
  {
    id: 'forest',
    name: 'Forest Green',
    primary: '#2d5a27',
    primaryStrong: '#1f4a1a',
    primarySoft: '#4a8a3f',
    secondary: '#6a9e5f',
    secondarySoft: '#a8cda0',
    surface: '#f2f7f1',
    surfaceStrong: '#ddeadb',
    surfaceMuted: '#c8dcc5',
    text: '#1a2e18',
    textMuted: '#4a6646',
    border: '#b8d0b4',
  },
  {
    id: 'burgundy',
    name: 'Burgundy',
    primary: '#6b1d2a',
    primaryStrong: '#55161f',
    primarySoft: '#9a3a4e',
    secondary: '#b06070',
    secondarySoft: '#d4a0ab',
    surface: '#f8f1f2',
    surfaceStrong: '#ecd9dc',
    surfaceMuted: '#dfc2c7',
    text: '#2e0f15',
    textMuted: '#7a4550',
    border: '#d4b0b8',
  },
  {
    id: 'plum',
    name: 'Plum',
    primary: '#5c2d6e',
    primaryStrong: '#4a2358',
    primarySoft: '#854f9a',
    secondary: '#9a6dae',
    secondarySoft: '#c8a8d6',
    surface: '#f6f1f8',
    surfaceStrong: '#e8daed',
    surfaceMuted: '#dac4e1',
    text: '#261230',
    textMuted: '#6e4580',
    border: '#cfb4d8',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    primary: '#1a5c7a',
    primaryStrong: '#124a64',
    primarySoft: '#3088aa',
    secondary: '#5aa0bb',
    secondarySoft: '#a0cede',
    surface: '#f0f6f9',
    surfaceStrong: '#d9e8ef',
    surfaceMuted: '#c2dae5',
    text: '#0d2a38',
    textMuted: '#3d6a80',
    border: '#b2ceda',
  },
  {
    id: 'copper',
    name: 'Copper',
    primary: '#8b4513',
    primaryStrong: '#6e360e',
    primarySoft: '#b06a30',
    secondary: '#c4884d',
    secondarySoft: '#ddb88a',
    surface: '#f9f5f0',
    surfaceStrong: '#eee3d5',
    surfaceMuted: '#e0d0bc',
    text: '#3a1c08',
    textMuted: '#7a5530',
    border: '#d4c0a8',
  },
  {
    id: 'slate',
    name: 'Slate Blue',
    primary: '#4a5568',
    primaryStrong: '#3a4355',
    primarySoft: '#6b7d95',
    secondary: '#8a9bb5',
    secondarySoft: '#b8c5d5',
    surface: '#f1f3f6',
    surfaceStrong: '#dde1e8',
    surfaceMuted: '#c9d0da',
    text: '#1a202c',
    textMuted: '#56617a',
    border: '#bcc5d2',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    primary: '#333333',
    primaryStrong: '#222222',
    primarySoft: '#555555',
    secondary: '#777777',
    secondarySoft: '#aaaaaa',
    surface: '#f2f2f2',
    surfaceStrong: '#e0e0e0',
    surfaceMuted: '#cccccc',
    text: '#111111',
    textMuted: '#555555',
    border: '#bbbbbb',
  },
  {
    id: 'sienna',
    name: 'Sienna',
    primary: '#804020',
    primaryStrong: '#663318',
    primarySoft: '#a06040',
    secondary: '#b88060',
    secondarySoft: '#d4b098',
    surface: '#f8f4f0',
    surfaceStrong: '#ece2d8',
    surfaceMuted: '#ddd0c2',
    text: '#351a0a',
    textMuted: '#7a5540',
    border: '#d0bfae',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    primary: '#2c3e50',
    primaryStrong: '#1a2a3a',
    primarySoft: '#4a6a88',
    secondary: '#6a8aaa',
    secondarySoft: '#a0b8cc',
    surface: '#f0f3f5',
    surfaceStrong: '#dae1e8',
    surfaceMuted: '#c4cfda',
    text: '#141e28',
    textMuted: '#4a5e72',
    border: '#b4c2d0',
  },
]

export const DEFAULT_SCHEME = COLOR_SCHEMES[0]

export function getSchemeById(id: string): ColorScheme {
  return COLOR_SCHEMES.find(s => s.id === id) || DEFAULT_SCHEME
}
